### ISSUE TITLE
Juggernaut [Axe]

### ISSUE THREAD

**Issue by HappenLTD** [TheMatrixNetwork/Server#6]
When someone's a juggernaut theres a skill that allows you to deal more 50 damage per hit to any armor while holding an axe.

This allows people to break any diamond armor in 4 hits.

It's mostly broken because juggernauts last a lot during combat and with this skill being as it is, we will just win every single fight as the opponent loses his armor in the next 5 seconds.

**Comment by TejasDesale** [comment]
in skills .yml the calulation is /2 make it /5

**Comment by CrashCringle12** [comment]
Let's actually discuss this.

This is what the Juggernaut passive and Heavy Strikes currently looks like:
  juggernaut-passive:
    scaling: def/2
    chance: def
  heavy-strikes:
    # Special Variables: durability
    required-level: 5
    scaling: (def / 2) + lvl
    cost: 100 * (lvl + 1)
    weapons:
      - "CONTAINS:AXE"

As Tejas proposed we could divide the scaling by 5 rather than 2. There is also the possibility to make the damage based on durability. @HappenLTD 

Is this cool beans or do you have another calculation in mind

**Comment by HappenLTD** [comment]
Sorry for the late response, and no, don't make the damage based on durability, that's quite ehhh.
I'd say lets divide the scaling by 5 like Tejas said and see how it goes.
